### ISSUE TITLE
Mixin apply for mod gcyr failed gcyr-common.mixins.json:EntityMixin from mod gcyr

### ISSUE THREAD

**Issue by baifeiajdj** [Argent-Matter/gcys#11]
[latest.log](https://github.com/Argent-Matter/gcyr/files/13870785/latest.log)

**Comment by screret** [comment]
conflict with lithium.

**Comment by Exzept1on** [comment]
Use this in canary config to fix crash
![image](https://github.com/Argent-Matter/gcyr/assets/52341158/20d87679-08e0-4d46-b780-2f326a02152d)

**Comment by EntityinArray** [comment]
> Use this in canary config to fix crash ![image](https://private-user-images.githubusercontent.com/52341158/297973982-20d87679-08e0-4d46-b780-2f326a02152d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzIyNTAsIm5iZiI6MTcwNjAzMTk1MCwicGF0aCI6Ii81MjM0MTE1OC8yOTc5NzM5ODItMjBkODc2NzktMDhlMC00ZDQ2LWI3ODAtMmYzMjZhMDIxNTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE3NDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YTcxMzA1ZjQ5MjA0MzA0ZGU2MTgwMGVkNmY4Y2U3YmQzMjg0YWI3NTEwYmRhODVjYTQ2ZDE4MTFlNWVhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WVQ2IVzBUz-Owa2z8-H8h_tIBL5dyrs4ArOf6H_h5fE)

Doesn't work for me, [latest.log](https://github.com/Argent-Matter/gcyr/files/14028093/latest.log)
![image](https://github.com/Argent-Matter/gcyr/assets/18554021/8f7a772a-80d7-4969-b582-bc0260de0354)
