### ISSUE TITLE
[Feature Req] - #gcyr:spacesuit tag & spacesuit upgrade template

### ISSUE THREAD

**Issue by Ghostipedia** [Argent-Matter/gcys#20]
Describe the feature

While the spacesuit is a great starting point, in the event a pack dev or player wishes to use their own armor or in the future GTM's armors. 

What I propose is a "Spacesuit Template" and Autogenned Smithing recipes that allow you to 'augment' any generic armor to work in space. (Via a tag potentially like #gcyr:spacesuit) - 
An Example recipe would just be **Generic Helm + Space Helm + template = Augmented Helm**

**Comment by screret** [comment]
idk how possible this is...

**Comment by screret** [comment]
it's possible 👍
