### ISSUE TITLE
None of the rocket parts are craftable

### ISSUE THREAD

**Issue by Wyrmlet** [Argent-Matter/gcys#23]
Title. This seems to show up in multiple modpacks, for example ATM gravitas 2 and terrafirmagreg. I am unsure if this is intentional or not at this point, as pretty much every other item in the mod has a crafting recipe.

**Comment by BUGProtectionAssociation** [comment]
Yes. We couldn`t craft them in ATMG

**Comment by screret** [comment]
weeelll there's nowhere to travel to with those parts yet. If you need recipes, do suggest some!
closing for now.
