### ISSUE TITLE
在mixin注入时与锂发生冲突

### ISSUE THREAD

**Issue by ct-yx** [Argent-Matter/gcys#33]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gcyr-fabric-1.20.1-0.1.3-aa

### Recipe Viewer Installed

REI

### Environment

启动的时候

### Cross-Mod Interaction

Yes

### Other Installed Mods

![Screenshot_2024-06-01-22-45-20-518_com estrongs android pop](https://github.com/Argent-Matter/gcyr/assets/122712983/73748c58-264c-4946-b81e-007e026fab64)

### Expected Behavior

mixin注入与锂不冲突

### Actual Behavior

@At("INVOKE") on net/minecraft/class_1297::gcyr$modifySpaceStationBorder with priority 1000 cannot inject into 
net/minecraft/class_1297::method_20736(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;... 
merged by me.jellysquid.mods.lithium.mixin.entity.collisions.movement.EntityMixin with priority 1000
[latest.log](https://github.com/user-attachments/files/15522211/latest.log)
[2024-06-01-7.log.gz](https://github.com/user-attachments/files/15522215/2024-06-01-7.log.gz)
[latest.log](https://github.com/user-attachments/files/15522217/latest.log)

### Steps to Reproduce

在1.20.1安装锂模组最新版本

**Comment by zVoltaic** [comment]
not exactly sure what happened here but its worth mentioning that fabric support for gtceu and gcyr has been discontinued so theres a fat chance itll probably never get fixed
