### ISSUE TITLE
Potassium carbonate  dust is not craftable

### ISSUE THREAD

**Issue by FriendlyCube** [Argent-Matter/gcys#35]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.3.a

### Recipe Viewer Installed

EMI

### Environment

server

### Cross-Mod Interaction

Yes

### Other Installed Mods

[TerraFirmaGreg](https://github.com/TerraFirmaGreg-Team/Modpack-Modern)

### Expected Behavior

![image](https://github.com/Argent-Matter/gcyr/assets/112543401/3947d382-7726-41f0-a1c9-1d28008ba0d1)

I expected to be able to craft Potassium carbonate 

### Actual Behavior

Potassium carbonate is not craftable, but it is used for crafting rockets (for kapton K)

### Steps to Reproduce

Check out the craft the Potassium carbonate

**Comment by Igor-Movchan** [comment]
true, same for me

**Comment by jmoiron** [comment]
This has been [fixed upstream](https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1/src/main/java/com/gregtechceu/gtceu/data/recipe/serialized/chemistry/AntidoteRecipes.java#L104-L109) and should be resolved when you update gtceu.
