### ISSUE TITLE
compat with ad astra and ad extendra

### ISSUE THREAD

**Issue by Mysticpasta1** [Argent-Matter/gcys#52]
### Cross-mod Integration

Ad Astra and Ad extendra

### Feature Description

be able to use gregicality rockets with ad astra and ad extendra orbits and planet, and ability to make space stations in the orbits too :D

**Comment by screret** [comment]
...why, though?

**Comment by Mysticpasta1** [comment]
I like the ad astra planets unless you guys add more

do you guys add the entire solar system

**Comment by zVoltaic** [comment]
just the 4 rocky planets atm, proxima centauri and a couple moons are coming in the next update
