### ISSUE TITLE
client crash when building rocket on server

### ISSUE THREAD

**Issue by jmoiron** [Argent-Matter/gcys#53]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Recipe Viewer Installed

EMI

### Environment

Dedicated Server

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Quantum Skies

### Expected Behavior

Selecting "scan rocket" produces a rocket entity and does not crash the client.

### Actual Behavior

Client crashes on rocket scan, and upon logging back in, the block adjacent to the scanner is a rocket entity but the rest of the blocks in the rocket is not.

### Steps to Reproduce

Attempt to scan a rocket on a dedicated server.

### Additional Information

scanner multiblock orientation is north/south

I also recorded the crash message on my repo:

https://github.com/jmoiron/quantum-skies/issues/18#issuecomment-2380385116

**Comment by Vaengence** [comment]
Just got linked to this in GTCEU Modern discord. Am experiencing this as well today. Currently on Monifactory 0.9.2 latest. 
https://imgur.com/cZQzZhQ
