### ISSUE TITLE
Rocket Scanner GUI

### ISSUE THREAD

**Issue by nutellabrot155** [Argent-Matter/gcys#57]
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.4.6

### Recipe Viewer Installed

None

### Environment

Dedicated Server and Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

GTCEU modern,Gregified Integration for Singleplayer
and Monifactory 0.9.7 for Dedi Server

### Expected Behavior

![Screenshot 2024-10-17 162851](https://github.com/user-attachments/assets/dd81ca6f-d20a-4537-a6ec-46ba8041c208)

### Actual Behavior

![Screenshot 2024-10-16 131808](https://github.com/user-attachments/assets/c0eeabe0-c365-416d-9de5-b7c1a50c4ed4)

### Steps to Reproduce

Open Rocket Scanner

**Comment by screret** [comment]
known issue, will be fixed in the next GT update. one of our (as in GTM) developers did a small mistake that only appears in specific machines like steam multiblocks and the rocket scanner.

**Comment by Spicierspace153** [comment]
fixed in gtm
