### ISSUE TITLE
Fabric 1.20.1 Access Widener Crash (Mod Version: 0.1.0.a)

### ISSUE THREAD

**Issue by TacoMonkey11** [Argent-Matter/gcys#7]
class_2400 = SimpleParticleType

[crash-2023-10-27_10.55.46-client.txt](https://github.com/Argent-Matter/gcyr/files/13190257/crash-2023-10-27_10.55.46-client.txt)

**Comment by screret** [comment]
fixed with latest dev build?

**Comment by TacoMonkey11** [comment]
Yes
